package io.quarkus.orbit.pulse.service;

import io.quarkus.orbit.pulse.model.ScoredPullRequest;
import jakarta.enterprise.context.ApplicationScoped;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;

@ApplicationScoped
public class ReportService {

    public String generateMarkdown(Map<String, List<ScoredPullRequest>> resultsByRepo) {
        var sb = new StringBuilder();
        String date = LocalDate.now().format(DateTimeFormatter.ISO_LOCAL_DATE);

        sb.append("# GitHub Pulse Report - %s\n\n".formatted(date));

        if (resultsByRepo.isEmpty()) {
            sb.append("No PRs exceeded the scoring threshold.\n");
            return sb.toString();
        }

        for (var entry : resultsByRepo.entrySet()) {
            String repo = entry.getKey();
            List<ScoredPullRequest> prs = entry.getValue();

            sb.append("## %s\n\n".formatted(repo));
            sb.append("| PR | Title | Author | Score | Labels |\n");
            sb.append("|---|---|---|---|---|\n");

            for (ScoredPullRequest scored : prs) {
                var pr = scored.pr();
                String labelsStr = pr.labels().isEmpty() ? "-" : String.join(", ", pr.labels());
                sb.append("| [#%d](%s) | %s | @%s | **%.0f** | %s |\n".formatted(
                        pr.number(),
                        pr.url(),
                        pr.title(),
                        pr.author(),
                        scored.score(),
                        labelsStr
                ));
            }

            sb.append("\n### Details\n\n");
            for (ScoredPullRequest scored : prs) {
                sb.append("**[#%d](%s) %s** (Score: %.0f)\n".formatted(
                        scored.pr().number(),
                        scored.pr().url(),
                        scored.pr().title(),
                        scored.score()
                ));
                for (var result : scored.ruleResults()) {
                    if (result.reason() != null) {
                        sb.append("  - %s\n".formatted(result.reason()));
                    }
                }
                sb.append("\n");
            }
        }

        sb.append("---\n*Generated by GitHub Pulse on %s*\n".formatted(date));
        return sb.toString();
    }
}
