package io.quarkus.orbit.pulse.service;

import io.quarkus.orbit.pulse.entity.RepositorySource;
import io.quarkus.orbit.pulse.model.ScoredPullRequest;
import jakarta.enterprise.context.ApplicationScoped;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;

@ApplicationScoped
public class ReportService {

    // Public records for platform report generation
    public record PlatformRepoReport(List<String> versions, List<PrWithVersions> prs) {}
    public record PrWithVersions(ScoredPullRequest scored, List<String> versions) {}

    private static final Map<RepositorySource, String> SECTION_HEADERS = Map.of(
            RepositorySource.UPSTREAM, "Upstream",
            RepositorySource.QUARKUS, "Quarkus",
            RepositorySource.QUARKIVERSE, "Quarkiverse"
    );

    public String generateMarkdown(Map<String, List<ScoredPullRequest>> resultsByRepo) {
        var sb = new StringBuilder();
        String date = LocalDate.now().format(DateTimeFormatter.ISO_LOCAL_DATE);

        sb.append("# GitHub Pulse Report - %s\n\n".formatted(date));

        if (resultsByRepo.isEmpty()) {
            sb.append("No PRs exceeded the scoring threshold.\n");
            return sb.toString();
        }

        for (var entry : resultsByRepo.entrySet()) {
            appendRepoSection(sb, entry.getKey(), entry.getValue());
        }

        sb.append("---\n*Generated by GitHub Pulse on %s*\n".formatted(date));
        return sb.toString();
    }

    public String generateReleaseReportMarkdown(String repoId, String tag, List<ScoredPullRequest> prs) {
        return generateReleaseReportMarkdown(repoId, tag, prs, true);
    }

    public String generateReleaseReportMarkdown(String repoId, String tag, List<ScoredPullRequest> prs, boolean details) {
        var sb = new StringBuilder();
        sb.append("# Release Report: %s %s\n\n".formatted(repoId, tag));

        if (prs.isEmpty()) {
            sb.append("No PRs found in release notes.\n");
            return sb.toString();
        }

        sb.append("**%d PRs in this release**\n\n".formatted(prs.size()));
        if (details) {
            appendRepoSection(sb, repoId, prs);
        } else {
            appendRepoSectionCompact(sb, repoId, prs);
        }

        String date = LocalDate.now().format(DateTimeFormatter.ISO_LOCAL_DATE);
        sb.append("---\n*Generated by GitHub Pulse on %s*\n".formatted(date));
        return sb.toString();
    }

    private void appendRepoSection(StringBuilder sb, String repoId, List<ScoredPullRequest> prs) {
        sb.append("#### %s\n\n".formatted(repoId));

        for (ScoredPullRequest scored : prs) {
            var pr = scored.pr();
            sb.append("- [#%d](%s) **%s** (Score: %.0f)\n".formatted(
                    pr.number(), pr.url(), pr.title(), scored.score()));
            if (scored.summary() != null) {
                sb.append("  > %s\n".formatted(scored.summary()));
            }
            for (var result : scored.ruleResults()) {
                if (result.reason() != null) {
                    sb.append("  - %s\n".formatted(result.reason()));
                }
            }
            sb.append("\n");
        }
    }

    private void appendRepoSectionCompact(StringBuilder sb, String repoId, List<ScoredPullRequest> prs) {
        sb.append("#### %s\n\n".formatted(repoId));

        for (ScoredPullRequest scored : prs) {
            var pr = scored.pr();
            sb.append("- [#%d](%s) **%s** (Score: %.0f)\n".formatted(
                    pr.number(), pr.url(), pr.title(), scored.score()));
            if (scored.summary() != null) {
                sb.append("  > %s\n".formatted(scored.summary()));
            }
            sb.append("\n");
        }
    }

    public String generatePlatformReportMarkdown(String title,
            Map<RepositorySource, Map<String, PlatformRepoReport>> sections) {
        var sb = new StringBuilder();
        sb.append("# Platform Report: %s\n\n".formatted(title));

        for (RepositorySource source : List.of(RepositorySource.UPSTREAM, RepositorySource.QUARKUS, RepositorySource.QUARKIVERSE)) {
            Map<String, PlatformRepoReport> repos = sections.getOrDefault(source, Map.of());
            if (repos.isEmpty()) continue;

            sb.append("## %s\n\n".formatted(SECTION_HEADERS.get(source)));

            for (var entry : repos.entrySet()) {
                String repoName = entry.getKey();
                PlatformRepoReport report = entry.getValue();
                boolean multipleVersions = report.versions().size() > 1;

                sb.append("### %s (%s)\n\n".formatted(repoName, String.join(", ", report.versions())));

                for (PrWithVersions prv : report.prs()) {
                    var pr = prv.scored().pr();
                    sb.append("- [#%d](%s) **%s** (Score: %.0f)".formatted(
                            pr.number(), pr.url(), pr.title(), prv.scored().score()));
                    if (multipleVersions) {
                        sb.append(" `%s`".formatted(String.join(", ", prv.versions())));
                    }
                    sb.append("\n");
                    if (prv.scored().summary() != null) {
                        sb.append("  > %s\n".formatted(prv.scored().summary()));
                    }
                    sb.append("\n");
                }
            }
        }

        String date = LocalDate.now().format(DateTimeFormatter.ISO_LOCAL_DATE);
        sb.append("---\n*Generated by GitHub Pulse on %s*\n".formatted(date));
        return sb.toString();
    }

    public void writeReport(String filename, String content) throws java.io.IOException {
        java.nio.file.Path reportDir = java.nio.file.Path.of("reports");
        java.nio.file.Files.createDirectories(reportDir);
        java.nio.file.Files.writeString(reportDir.resolve(filename), content);
    }
}
