package io.quarkus.orbit.pulse.service;

import io.quarkus.orbit.pulse.entity.RepositorySource;
import io.quarkus.orbit.pulse.model.PullRequestData;
import io.quarkus.orbit.pulse.model.ScoredPullRequest;
import io.quarkus.orbit.pulse.scoring.ScoringRule;
import io.quarkus.orbit.pulse.scoring.rules.PrCategory;
import io.quarkus.orbit.pulse.service.ReportService.PlatformRepoReport;
import io.quarkus.orbit.pulse.service.ReportService.PrWithVersions;
import org.junit.jupiter.api.Test;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

class ReportServiceTest {

    private final ReportService service = new ReportService();

    @Test
    void existingGenerateMarkdownStillWorks() {
        var pr = new PullRequestData("o", "r", 1, "Title", "url", "a", "d", 10, 5, 1, List.of(), List.of());
        var scored = new ScoredPullRequest(pr, 50.0, List.of(), Map.of(), null, null);

        String markdown = service.generateMarkdown(Map.of("o/r", List.of(scored)));
        assertTrue(markdown.contains("o/r"));
        assertTrue(markdown.contains("#1"));
    }

    @Test
    void generateReleaseReportMarkdownContainsRepoAndTag() {
        var pr = new PullRequestData("quarkusio", "quarkus", 44000,
                "Fix CDI regression", "https://github.com/quarkusio/quarkus/pull/44000",
                "dev1", "Fixes a CDI issue", 30, 5, 2, List.of("extensions/cdi/runtime/src/Main.java"), List.of());

        var scored = new ScoredPullRequest(pr, 82.0,
                List.of(new ScoringRule.ScoringResult("category", 100, 100, "Category: BUG_FIX")),
                Map.of(), PrCategory.BUG_FIX, "Fixes a CDI injection regression");

        String markdown = service.generateReleaseReportMarkdown("quarkusio/quarkus", "3.18.0", List.of(scored));

        assertTrue(markdown.contains("quarkusio/quarkus"));
        assertTrue(markdown.contains("3.18.0"));
        assertTrue(markdown.contains("#44000"));
        assertTrue(markdown.contains("Fix CDI regression"));
        assertTrue(markdown.contains("Fixes a CDI injection regression"));
    }

    @Test
    void generateReleaseReportMarkdownHandlesEmptyPrList() {
        String markdown = service.generateReleaseReportMarkdown("quarkusio/quarkus", "3.18.0", List.of());

        assertTrue(markdown.contains("quarkusio/quarkus"));
        assertTrue(markdown.contains("3.18.0"));
        assertTrue(markdown.contains("No PRs"));
    }

    @Test
    void generatePlatformReportMarkdownWithMultipleSections() {
        var pr1 = new PullRequestData("smallrye", "smallrye-mutiny", 123,
                "Fix backpressure", "https://github.com/smallrye/smallrye-mutiny/pull/123",
                "dev1", "", 10, 5, 1, List.of(), List.of());
        var scored1 = new ScoredPullRequest(pr1, 85.0, List.of(), Map.of(), PrCategory.BUG_FIX, "Fixes backpressure");

        var pr2 = new PullRequestData("quarkusio", "quarkus", 44000,
                "Improve startup", "https://github.com/quarkusio/quarkus/pull/44000",
                "dev2", "", 30, 5, 2, List.of(), List.of());
        var scored2 = new ScoredPullRequest(pr2, 90.0, List.of(), Map.of(), PrCategory.ENHANCEMENT, "Faster startup");

        var sections = new LinkedHashMap<RepositorySource, Map<String, PlatformRepoReport>>();

        var upstreamRepos = new LinkedHashMap<String, PlatformRepoReport>();
        upstreamRepos.put("smallrye-mutiny", new PlatformRepoReport(
                List.of("2.8.0"),
                List.of(new PrWithVersions(scored1, List.of("2.8.0")))));
        sections.put(RepositorySource.UPSTREAM, upstreamRepos);

        var quarkusRepos = new LinkedHashMap<String, PlatformRepoReport>();
        quarkusRepos.put("quarkus", new PlatformRepoReport(
                List.of("3.38.0.CR1", "3.38.0"),
                List.of(new PrWithVersions(scored2, List.of("3.38.0.CR1", "3.38.0")))));
        sections.put(RepositorySource.QUARKUS, quarkusRepos);

        String markdown = service.generatePlatformReportMarkdown("Quarkus 3.38.0.CR1, 3.38.0", sections);

        assertTrue(markdown.contains("# Platform Report: Quarkus 3.38.0.CR1, 3.38.0"));
        assertTrue(markdown.contains("## Upstream"));
        assertTrue(markdown.contains("### smallrye-mutiny (2.8.0)"));
        assertTrue(markdown.contains("#123"));
        assertTrue(markdown.contains("## Quarkus"));
        assertTrue(markdown.contains("### quarkus (3.38.0.CR1, 3.38.0)"));
        assertTrue(markdown.contains("#44000"));
        // Multi-version repo shows version tags on PRs
        assertTrue(markdown.contains("`3.38.0.CR1, 3.38.0`"));
        // Single-version repo does NOT show version tags on PRs
        assertFalse(markdown.contains("`2.8.0`"));
        assertTrue(markdown.contains("Generated by GitHub Pulse"));
    }

    @Test
    void generatePlatformReportMarkdownSkipsEmptySections() {
        var sections = new LinkedHashMap<RepositorySource, Map<String, PlatformRepoReport>>();
        sections.put(RepositorySource.UPSTREAM, new LinkedHashMap<>());

        var quarkusRepos = new LinkedHashMap<String, PlatformRepoReport>();
        var pr = new PullRequestData("quarkusio", "quarkus", 100,
                "Title", "url", "author", "", 10, 5, 1, List.of(), List.of());
        var scored = new ScoredPullRequest(pr, 70.0, List.of(), Map.of(), null, "Summary");
        quarkusRepos.put("quarkus", new PlatformRepoReport(
                List.of("3.38.0"),
                List.of(new PrWithVersions(scored, List.of("3.38.0")))));
        sections.put(RepositorySource.QUARKUS, quarkusRepos);

        String markdown = service.generatePlatformReportMarkdown("Quarkus 3.38.0", sections);

        assertFalse(markdown.contains("## Upstream"));
        assertTrue(markdown.contains("## Quarkus"));
    }
}
